from .point import Point
from .line import Line
from .shape import Shape
from .rectangle import Rectangle
from .square import Square
from .triangle import Triangle
from .isosceles import IsoscelesTriangle
from .equilateral import Equilateral
from .scalene import Scalene
